"""Add success column to SecurityLog

Revision ID: 03fc6caf29de
Revises: add_encrypted_calendly_token
Create Date: 2025-06-20 11:21:08.493925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fc6caf29de'
down_revision = 'add_encrypted_calendly_token'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('success', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_log', schema=None) as batch_op:
        batch_op.drop_column('success')

    # ### end Alembic commands ###
