"""Add RecurringAppointment table

Revision ID: 14befc8bd3a5
Revises: b6144efe6b6a
Create Date: 2025-04-17 11:23:45.903052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14befc8bd3a5'
down_revision = 'b6144efe6b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('recurrence_type', sa.String(length=50), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=False),
    sa.Column('treatment_type', sa.String(length=150), nullable=False, server_default='Standard Session'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('fee_charged', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
    sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now(), onupdate=sa.func.now()),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_appointment')
    # ### end Alembic commands ###
