"""Add clinic fields to User model

Revision ID: 17c4a0e4f99e
Revises: 4a211a0f03e6
Create Date: 2025-06-13 09:27:08.201157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c4a0e4f99e'
down_revision = '4a211a0f03e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinic_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('clinic_address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('clinic_phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('clinic_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('clinic_website', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('clinic_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('calendly_api_key', sa.String(length=255), nullable=True))
        batch_op.drop_column('calendly_api_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendly_api_token', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('calendly_api_key')
        batch_op.drop_column('clinic_description')
        batch_op.drop_column('clinic_website')
        batch_op.drop_column('clinic_email')
        batch_op.drop_column('clinic_phone')
        batch_op.drop_column('clinic_address')
        batch_op.drop_column('clinic_name')

    # ### end Alembic commands ###
