"""add_plan_type_to_plans

Revision ID: 2eaa5641f5ff
Revises: add_dashboard_mode_simple
Create Date: 2025-08-04 22:31:26.030665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eaa5641f5ff'
down_revision = 'add_dashboard_mode_simple'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_type', sa.String(length=20), nullable=False, server_default='individual'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('plan_type')

    # ### end Alembic commands ###
