"""Add stripe_customer_id to User model

Revision ID: 333a1b7e6f8f
Revises: 02268713afe2
Create Date: 2025-05-26 23:48:01.752056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333a1b7e6f8f'
down_revision = '02268713afe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_stripe_customer_id'), ['stripe_customer_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_stripe_customer_id'))
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
