"""Add contribution_base field to User model

Revision ID: 4a058e0663b9
Revises: 17c4a0e4f99e
Create Date: 2025-06-13 10:29:26.875674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a058e0663b9'
down_revision = '17c4a0e4f99e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contribution_base', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contribution_base')

    # ### end Alembic commands ###
