"""add_referral_fields_to_patient

Revision ID: 4a928bc93b44
Revises: 3ee95b6c9aa6
Create Date: 2025-09-10 22:53:50.546197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a928bc93b44'
down_revision = '3ee95b6c9aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referred_by_patient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referred_by_name', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('referral_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_patient_referred_by_patient_id', 'patient', ['referred_by_patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patient_referred_by_patient_id', type_='foreignkey')
        batch_op.drop_column('referral_notes')
        batch_op.drop_column('referred_by_name')
        batch_op.drop_column('referred_by_patient_id')

    # ### end Alembic commands ###
