"""Add practitioner_limit to Plan model

Revision ID: 69c52b59d914
Revises: 333a1b7e6f8f
Create Date: 2025-05-28 10:13:35.919746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c52b59d914'
down_revision = '333a1b7e6f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('practitioner_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('practitioner_limit')

    # ### end Alembic commands ###
