"""Add has_unlimited_access field to User model

Revision ID: 7ac1f468c109
Revises: 1ef5262c8c18
Create Date: 2025-06-23 02:51:12.323745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac1f468c109'
down_revision = '1ef5262c8c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_unlimited_access', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_unlimited_access')

    # ### end Alembic commands ###
