"""remove_dashboard_mode_column

Revision ID: 80922477c9bf
Revises: 2eaa5641f5ff
Create Date: 2025-08-04 22:39:57.208992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80922477c9bf'
down_revision = '2eaa5641f5ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dashboard_mode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dashboard_mode', sa.String(length=20), nullable=False, server_default='individual'))

    # ### end Alembic commands ###
