"""Add location, visit_type, fee_charged, payment_method to Treatment

Revision ID: 819cc60fee52
Revises: b6144efe6b6a
Create Date: 2025-04-14 16:08:28.912852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819cc60fee52'
down_revision = 'b6144efe6b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('visit_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fee_charged', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('fee_charged')
        batch_op.drop_column('visit_type')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
