"""Update UserConsent model fields

Revision ID: a9ca7a251865
Revises: 5ad53f2be9cb
Create Date: 2025-06-13 10:59:11.739933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ca7a251865'
down_revision = '5ad53f2be9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_consent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('purpose', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('given_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_user_consent_user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('consent_type')
        batch_op.drop_column('consent_date')
        batch_op.drop_column('consent_version')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('consent_text')

    # Make columns non-nullable after adding them
    with op.batch_alter_table('user_consent', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)
        batch_op.alter_column('purpose', nullable=False)
        batch_op.alter_column('given_at', nullable=False)
        batch_op.alter_column('is_active', nullable=False, server_default='1')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_consent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consent_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('consent_version', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('consent_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('consent_type', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('fk_user_consent_user_id', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('notes')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('given_at')
        batch_op.drop_column('purpose')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
