"""Add fiscal configuration fields to User model

Revision ID: add_fiscal_fields_only
Revises: fix_patient_name_length
Create Date: 2025-06-22 23:35:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_fiscal_fields_only'
down_revision = 'fix_patient_name_length'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_year', sa.Integer(), nullable=True, default=2025))
        batch_op.add_column(sa.Column('tax_brackets', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('autonomo_contribution_rate', sa.Float(), nullable=True, default=0.314))
        batch_op.add_column(sa.Column('tax_rate', sa.Float(), nullable=True, default=0.19))
        batch_op.add_column(sa.Column('clinic_fee_rate', sa.Float(), nullable=True, default=0.30))
        batch_op.add_column(sa.Column('currency_symbol', sa.String(length=5), nullable=True, default='€'))
        batch_op.add_column(sa.Column('revenue_currency_symbol', sa.String(length=5), nullable=True, default='£'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('revenue_currency_symbol')
        batch_op.drop_column('currency_symbol')
        batch_op.drop_column('clinic_fee_rate')
        batch_op.drop_column('tax_rate')
        batch_op.drop_column('autonomo_contribution_rate')
        batch_op.drop_column('tax_brackets')
        batch_op.drop_column('tax_year')

    # ### end Alembic commands ### 