"""Add Calendly fields to User and user_id to UnmatchedCalendlyBooking

Revision ID: b383bd3bab2f
Revises: e1ba31141930
Create Date: 2025-05-11 14:02:49.276545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b383bd3bab2f'
down_revision = 'e1ba31141930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unmatched_calendly_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_unmatched_calendly_booking_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendly_api_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('calendly_user_uri', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('calendly_user_uri')
        batch_op.drop_column('calendly_api_token')

    with op.batch_alter_table('unmatched_calendly_booking', schema=None) as batch_op:
        batch_op.drop_constraint('fk_unmatched_calendly_booking_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
