"""Remove next_appointment column manually

Revision ID: b6144efe6b6a
Revises: 
Create Date: 2025-04-12 11:13:21.135743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6144efe6b6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.alter_column('treatment_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('provider',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('body_chart_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('next_appointment')
        batch_op.drop_column('progress_notes')
        batch_op.drop_column('description')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('progress_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('next_appointment', sa.DATETIME(), nullable=True))
        batch_op.alter_column('body_chart_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('provider',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('treatment_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
