"""Initial migration with all models

Revision ID: bda3e0c6096c
Revises: 
Create Date: 2025-04-26 11:31:47.884757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda3e0c6096c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjust! ###
    # Removed incorrect drop_table and drop_column operations
    # op.drop_table('patient_exercise')
    # op.drop_table('exercise')
    # with op.batch_alter_table('patient', schema=None) as batch_op:
    #    batch_op.drop_column('address')

    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendly_invitee_uri', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_treatment_calendly_invitee_uri'), ['calendly_invitee_uri'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatment_calendly_invitee_uri'))
        batch_op.drop_column('calendly_invitee_uri')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.TEXT(), nullable=True))

    op.create_table('exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('instructions', sa.TEXT(), nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('muscle_group', sa.VARCHAR(length=100), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=20), nullable=True),
    sa.Column('position', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('patient_exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('assigned_date', sa.DATETIME(), nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sets', sa.INTEGER(), nullable=True),
    sa.Column('reps', sa.INTEGER(), nullable=True),
    sa.Column('duration', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('completion_status', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
