"""Add portal user link to Patient model

Revision ID: c879d57af6f4
Revises: ff42825be70f
Create Date: 2025-05-09 10:20:09.034770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c879d57af6f4'
down_revision = 'ff42825be70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portal_user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_patient_portal_user_id', ['portal_user_id'])
        batch_op.create_foreign_key('fk_patient_portal_user_id_user', 'user', ['portal_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patient_portal_user_id_user', type_='foreignkey')
        batch_op.drop_constraint('uq_patient_portal_user_id', type_='unique')
        batch_op.drop_column('portal_user_id')

    # ### end Alembic commands ###
