"""add updated_at to patient model

Revision ID: c99abce47ea0
Revises: bda3e0c6096c
Create Date: 2025-05-02 16:16:07.513314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99abce47ea0'
down_revision = 'bda3e0c6096c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
