"""add_dry_needling_preference_to_patient

Revision ID: dbff4a688163
Revises: 4a928bc93b44
Create Date: 2025-09-11 00:45:31.661166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbff4a688163'
down_revision = '4a928bc93b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dry_needling_preference', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('dry_needling_preference')

    # ### end Alembic commands ###
