"""Add user_id to PracticeReport

Revision ID: e1ba31141930
Revises: c879d57af6f4
Create Date: 2025-05-11 11:34:40.014873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ba31141930'
down_revision = 'c879d57af6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_practice_reports_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_practice_reports_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
