"""Add payment_method to RecurringAppointment

Revision ID: eacf40bd2a7d
Revises: 8da0a7026c14
Create Date: 2025-04-17 11:42:02.347713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacf40bd2a7d'
down_revision = '8da0a7026c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_appointment', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
