name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_physio
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_physio" >> $GITHUB_ENV
          echo "TEST_DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_physio" >> $GITHUB_ENV
          echo "SECRET_KEY=test-secret-key-for-ci" >> $GITHUB_ENV
          echo "FERNET_SECRET_KEY=test-fernet-key-for-ci-32-chars-long" >> $GITHUB_ENV
          echo "STRIPE_SECRET_KEY=sk_test_dummy" >> $GITHUB_ENV
          echo "STRIPE_WEBHOOK_SECRET=whsec_dummy" >> $GITHUB_ENV
          echo "FLASK_ENV=testing" >> $GITHUB_ENV

      - name: Wait for PostgreSQL
        run: |
          while ! pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Fix database migration
        run: |
          echo "🔧 Arreglando migración de base de datos..."
          python fix_migration_github_actions.py

      - name: Run tests
        run: |
          echo "🧪 Ejecutando tests..."
          python -m pytest tests/ -v --tb=short --maxfail=10
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_physio
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_physio
          SECRET_KEY: test-secret-key-for-ci
          FERNET_SECRET_KEY: test-fernet-key-for-ci-32-chars-long
          STRIPE_SECRET_KEY: sk_test_dummy
          STRIPE_WEBHOOK_SECRET: whsec_dummy
          FLASK_ENV: testing
